name = "standard"
description = "A standardized resume theme."
license = "MIT"
homepage = "https://github.com/resume-rs/themes-standard"
min_version = "0.19.0"
demo = "https://aa.resume.rs"

[author]
name = "Anibal Aguila"
homepage = "https://github.com/anibal-aguila"

[extra]
